"""add needs_manual_review and ai_error_detail to emails

Revision ID: 49109da49679
Revises: 8a44d0e6cf54
Create Date: 2026-07-07 22:05:25.051899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49109da49679'
down_revision: Union[str, None] = '8a44d0e6cf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('needs_manual_review', sa.Boolean(), nullable=True))
    op.add_column('emails', sa.Column('ai_error_detail', sa.Text(), nullable=True))
    op.create_index(op.f('ix_emails_needs_manual_review'), 'emails', ['needs_manual_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_needs_manual_review'), table_name='emails')
    op.drop_column('emails', 'ai_error_detail')
    op.drop_column('emails', 'needs_manual_review')
    # ### end Alembic commands ###
